# Generated by Django 5.0.2 on 2024-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Due_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
