# Generated by Django 5.0.2 on 2024-04-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0003_alter_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Due_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='User',
            new_name='user',
        ),
    ]
